#! /bin/sh

stopGoingToOtherHandlers() {
  echo 'done successfully'
  exit 0;
}

basePath() {
  echo "${PROJECT_PATH:-$(dirname "$0")/..}"
}

# gets the path to the given controller
controller() {
  echo "$(basePath)"/controllers/"${1}"
}

# if the demanded action is the target one then
# the given controller with given parameters will be called
# action "demanded-action" "target-action" "controller" "parameters ..."
action() {
  if [ "${1}" = "${2}" ]; then
    $(controller "${3}") "${4}" "${5}" "${6}" "${7}"
    stopGoingToOtherHandlers
  fi
}

# gets the path of the given template
# usage: template "letter"
# template "template name without .template suffix"
template() {
  echo "$(basePath)"/templates/"${1}".template;
}

# gets library files
# usage: library "library-name"
library() {
  echo "$(basePath)"/lib/"${1}";
}

# gets utils files
# usage: utils "printer"
# usage: $(utils)/printer
utils() {
  echo "$(basePath)"/utils/"${1}"
}